aws:
  access.key:
  secret.key:

azure:
  storage.key: ""
  storage.account:

backups:
  aws.to.azure:
    amazon-bucket: azure-container

local.sourcelist: fullpath/sourcelist
temp.cloud.store: fullpath/assets
